import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/_components/navbar";
import { Particles } from "@/components/ui/particles";
import { Footer } from "@/_components/footer";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "Portfolio Jessi Owe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className} antialiased`}>
                <div className="relative flex flex-col bg-[radial-gradient(ellipse_at_center,var(--tw-gradient-stops))] from-slate-950 via-blue-950 to-purple-900">
                    <Particles
                        className="absolute inset-0 -z-10"
                        quantity={150}
                        ease={80}
                        color="#ffffff"
                    />
                    <Navbar />
                    <main className="flex-1 min-h-screen container mx-auto">
                        {children}
                    </main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
